import type { Metadata } from "next"
import type * as React from "react"

import { ThemeProvider } from "@/components/theme-provider"
import { fontVariableClassNames } from "@/lib/fonts"
import { cn } from "@/lib/utils"

import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en-GB" suppressHydrationWarning>
      <body className={cn(fontVariableClassNames, "antialiased")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
